FMS-main/FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name='home'),
    path('', include('authentication.urls')),
    path('profile/', include('user_profile.urls')),
    path('campaigns/', include('campaigns.urls')),
    path('user_management/', include('user_management.urls', namespace='user_management')),
    path('', include('analytics.urls', namespace='analytics')),
]

FMS-main/campaigns/urls.py
from . import views
from django.urls import path
from .views import CampaignListView

app_name = 'campaigns'

urlpatterns = [
    path('', views.campaign_list, name='campaign_list'),
    path('<int:campaign_id>/', views.campaign_detail, name='campaign_detail'),
    path('create/', views.campaign_create, name='campaign_create'),
    path('<int:campaign_id>/edit/', views.campaign_update, name='campaign_update'),
    path('all', CampaignListView.as_view(), name='campaign-list-api'),
]

FMS-main/campaigns/models.py
from django.db import models
from authentication.models import CustomUser

class Campaign(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    goal_amount = models.DecimalField(max_digits=12, decimal_places=2)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='created_campaigns')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def total_funded(self):
        return sum(funding.amount for funding in self.fundings.all())

    def __str__(self):
        return self.name

class Funding(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='fundings')
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE, related_name='fundings')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    funded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.email} funded {self.amount} to {self.campaign.name}"

FMS-main/campaigns/forms.py
# campaigns/forms.py
from django import forms
from .models import Campaign, Funding

class CampaignForm(forms.ModelForm):
    class Meta:
        model = Campaign
        fields = ['name', 'description', 'goal_amount']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-color focus:border-primary-color'}),
            'description': forms.Textarea(attrs={'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-color focus:border-primary-color'}),
            'goal_amount': forms.NumberInput(attrs={'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-color focus:border-primary-color'}),
        }


class FundingForm(forms.ModelForm):
    class Meta:
        model = Funding
        fields = ['amount']
        widgets = {
            'amount': forms.NumberInput(attrs={
                'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-color focus:border-primary-color'
            }),
        }

FMS-main/campaigns/views.py
# campaigns/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from .forms import CampaignForm, FundingForm
from .models import Campaign
from django.contrib import messages
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Campaign
from .serializers import CampaignSerializer

# List all campaigns
def campaign_list(request):
    campaigns = Campaign.objects.all()
    return render(request, 'campaign_list.html', {'campaigns': campaigns})

class CampaignListView(APIView):
    def get(self, request):
        campaigns = Campaign.objects.all()
        serializer = CampaignSerializer(campaigns, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

# Create new campaign - only for Admin role
@login_required
def campaign_create(request):
    if request.user.role != 'Admin':
        return HttpResponseForbidden("You do not have permission to create a campaign.")
    
    if request.method == 'POST':
        form = CampaignForm(request.POST)
        if form.is_valid():
            campaign = form.save(commit=False)
            campaign.created_by = request.user
            campaign.save()
            return redirect('campaigns:campaign_list')
    else:
        form = CampaignForm()
    return render(request, 'campaign_form.html', {'form': form})


@login_required
def campaign_detail(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)
    form = FundingForm()
    if request.method == 'POST':
        form = FundingForm(request.POST)
        if form.is_valid():
            funding = form.save(commit=False)
            funding.campaign = campaign
            funding.user = request.user
            funding.save()
            return redirect('campaigns:campaign_detail', campaign_id=campaign.id)

    context = {
        'campaign': campaign,
        'form': form,
        'total_funded': campaign.total_funded(),
    }
    return render(request, 'campaign_detail.html', context)

@login_required
def campaign_update(request, campaign_id):
    campaign = get_object_or_404(Campaign, id=campaign_id)

    # Check if the user is the creator of the campaign or an admin
    if request.user != campaign.created_by and request.user.role != 'Admin':
        return HttpResponseForbidden("You do not have permission to update this campaign.")

    if request.method == 'POST':
        form = CampaignForm(request.POST, instance=campaign)
        if form.is_valid():
            form.save()
            messages.success(request, "Campaign updated successfully.")
            return redirect('campaigns:campaign_detail', campaign_id=campaign.id)
    else:
        form = CampaignForm(instance=campaign)

    context = {
        'form': form,
        'campaign': campaign
    }
    return render(request, 'campaign_update_form.html', context)

FMS-main/campaigns/templates/campaign_detail.html
{% extends 'base.html' %}

{% block title %}Campaign Details{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto p-8 mt-10 bg-white rounded-lg shadow-md">
 <div class="flex items-center justify-between mb-6">
  <h1 class="text-3xl font-bold text-center text-primary-color">{{ campaign.name }}</h1>
  {% if user.role == 'Admin' %}
  <a href="{% url 'campaigns:campaign_update' campaign.id %}" class="bg-green-400 text-white px-4 py-2 rounded">Edit</a>
  {% endif %}
 </div>
  <div class="space-y-4 flex flex-wrap gap-x-8">
    <div>
      <h3 class="font-semibold text-gray-700">Description</h3>
      <p class="text-gray-600">{{ campaign.description }}</p>
    </div>
    <!-- <div>
      <h3 class="font-semibold text-gray-700">Goal Amount</h3>
      <p class="text-gray-600">${{ campaign.goal_amount }}</p>
    </div> -->
    <div>
      <h3 class="font-semibold text-gray-700">Total Paid</h3>
      <p class="text-gray-600">${{ campaign.goal_amount }}</p>
    </div>
    <div>
      <h3 class="font-semibold text-gray-700">Created By</h3>
      <p class="text-gray-600">{{ campaign.created_by.first_name }} {{ campaign.created_by.last_name }}</p>
    </div>
    <div>
      <h3 class="font-semibold text-gray-700">Created At</h3>
      <p class="text-gray-600">{{ campaign.created_at|date:"M d, Y" }}</p>
    </div>
  </div>

  <!-- Funding Form -->
  <div class="mt-6">
   
    <form method="POST" class="space-y-4">
      <!-- {% csrf_token %}
      {{ form.amount.label_tag }}
      {{ form.amount }} -->
     <div class="flex items-center justify-between mt-6">
      
      <div class="">
        <a href="{% url 'campaigns:campaign_list' %}" class="bg-green-400 text-white px-4 py-3 rounded">Back to Routes</a>
      </div>
     </div>
    </form>
  </div>
</div>
{% endblock %}

FMS-main/campaigns/templates/campaign_form.html
{% extends 'base.html' %}

{% block title %}Create Campaign{% endblock %}

{% block content %}
{% load form_tags %}

<div class="max-w-4xl mx-auto p-8 mt-10 bg-white rounded-lg shadow-md">
  <h1 class="text-3xl font-bold text-center text-primary-color mb-6">Create a New Route</h1>

  <form method="POST" class="space-y-6">
    {% csrf_token %}
    
    <div>
      <label for="name" class="block text-sm font-semibold text-gray-700">Route Name</label>
      {{ form.name|add_class:"w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-color focus:border-primary-color" }}
    </div>

    <div>
      <label for="description" class="block text-sm font-semibold text-gray-700">Description</label>
      {{ form.description|add_class:"w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-color focus:border-primary-color" }}
    </div>

    <div>
      <label for="goal_amount" class="block text-sm font-semibold text-gray-700">Transport Amount ($)</label>
      {{ form.goal_amount|add_class:"w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-color focus:border-primary-color" }}
    </div>

    <div class="flex justify-between">
      <button type="submit" class="bg-green-400 text-white px-4 py-2 rounded">Create route</button>
      <a href="{% url 'campaigns:campaign_list' %}" class="text-gray-500 hover:text-gray-700">Cancel</a>
    </div>
  </form>
</div>
{% endblock %}

FMS-main/campaigns/templates/campaign_list.html
{% extends 'base.html' %}

{% block title %}Campaigns{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto p-8 mt-10 bg-white rounded-lg shadow-md">
  <h1 class="text-3xl font-bold text-center text-primary-color mb-6">Routes</h1>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    {% for campaign in campaigns %}
      <div class="border border-gray-300 rounded-lg p-4 shadow">
        <h2 class="text-xl font-semibold text-gray-800">{{ campaign.name }}</h2>
        <p class="text-gray-600 mb-2">{{ campaign.description|truncatewords:20 }}</p>
        <p class="text-gray-600"><strong>Created by:</strong> {{ campaign.created_by.first_name }} {{ campaign.created_by.last_name }}</p>
        <p class="text-gray-500 text-sm"><strong>Created at:</strong> {{ campaign.created_at|date:"M d, Y" }}</p>
        <a href="{% url 'campaigns:campaign_detail' campaign.id %}" class="mt-4 inline-block bg-green-400 text-white px-4 py-2 rounded">View Details</a>
      </div>
    {% empty %}
      <p class="text-gray-500">No campaigns available.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

FMS-main/campaigns/templates/campaign_update_form.html
<!-- templates/campaigns/campaign_update_form.html -->
{% extends 'base.html' %}

{% block title %}Edit Campaign{% endblock %}

{% block content %}
<div class="max-w-4xl mx-auto p-8 mt-10 bg-white rounded-lg shadow-md">
    <h1 class="text-3xl font-bold text-center text-green-500 mb-6">Edit Campaign</h1>

    <form method="POST" class="space-y-6">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="flex justify-between">
            <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded">Update Campaign</button>
            <a href="{% url 'campaigns:campaign_detail' campaign.id %}" class="text-gray-500 hover:text-gray-700">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}